import localFont from "next/font/local";
import "./globals.css";
import HeaderComponent from "./Component/common/headerComponent";
import FooterComponent from "./component/common/footerComponent";
import { ToastContainer } from "react-toastify";
import { ContextProvider } from "./context/contextprovider"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextProvider >
          <HeaderComponent />
          {children}
          <FooterComponent />
          <ToastContainer />
        </ContextProvider>

      </body>
    </html>
  );
}
